### ISSUE TITLE
Coq 8.11 branch compilation failure

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#11954]
#### Description of the problem

Last night, all our CI cron jobs that build Coq 8.11 failed. Due to parallel builds, the output is not entirely deterministic; here is one that seems to have most error messages:
```
 [ERROR] The compilation of coq failed at "/usr/bin/make -j20".
#=== ERROR while compiling coq.8.11.dev =======================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(git+https://github.com/coq/coq.git#v8.11#993b698a)
# path                 /builds/iris/examples/opamroot/ocaml-base-compiler.4.08.1/.opam-switch/build/coq.8.11.dev
# command              /usr/bin/make -j20
# exit-code            2
# env-file             /builds/iris/examples/opamroot/log/coq-435-982793.env
# output-file          /builds/iris/examples/opamroot/log/coq-435-982793.out
### output ###
# /builds/iris/examples/opamroot/ocaml-base-compiler.4.08.1/lib/ocaml/caml/signals.h:55:60: error: unknown type name 'sigset_t'
# [...]
#                                                             ^~~~~~~~
# In file included from coq_memory.h:15:0,
#                  from coq_interp.c:28:
# /builds/iris/examples/opamroot/ocaml-base-compiler.4.08.1/lib/ocaml/caml/fail.h:45:3: error: unknown type name 'sigjmp_buf'
#    sigjmp_buf buf;
#    ^~~~~~~~~~
# Makefile.build:344: recipe for target 'kernel/byterun/coq_interp.o' failed
# make[1]: *** [kernel/byterun/coq_interp.o] Error 2
# make[1]: Leaving directory '/builds/iris/examples/opamroot/ocaml-base-compiler.4.08.1/.opam-switch/build/coq.8.11.dev'
# Makefile:177: recipe for target 'submake' failed
# make: *** [submake] Error 2
```

#### Coq Version

8.11 branch (commit 993b698a)

**Comment by RalfJung** [comment]
Uh, that's really strange, nothing landed on the 8.11 branch yesterday, so how can this fail now but did not fail before...

**Comment by RalfJung** [comment]
Ah no, I looked at the wrong thing (the latest commit on the branch was "committed" earlier, but landed recently). Here's the branch diff between the last version that worked on our CI, and the first that failed: https://github.com/coq/coq/compare/ce6bbee2...993b698

Some of these do indeed touch C code, so is is at least plausible they might be the source of this problem.
Cc @silene @ppedrot

**Comment by silene** [comment]
I guess the 8.11 branch is missing #11809.

**Comment by RalfJung** [comment]
Ah, that would explain why those of our nightly jobs that build Coq master (but otherwise use exactly the same setup) still work fine.

**Comment by ppedrot** [comment]
The backport is on its way, I pushed it yesterday but the CI got stuck as usual. It'll be in in 2 to 3 hours.

**Comment by RalfJung** [comment]
@ppedrot looks like that did not work? Our nightly builds are still failing.

**Comment by ppedrot** [comment]
I have problems with the Windows CI because one of the required package is currently down :/

**Comment by RalfJung** [comment]
Is there any news on this? I have no resorted to [a gross hack](https://gitlab.mpi-sws.org/iris/opam/-/commit/9141267b4208cc98564468d84c8c93c9c34c52af) to keep our CI going...

**Comment by ppedrot** [comment]
I've just pushed the backport. It was not easy, since the windows workers decided against compilation this week.

**Comment by ppedrot** [comment]
Can you confirm that I can close this btw?

**Comment by RalfJung** [comment]
Yes things seem to work again now. Thanks!
