### ISSUE TITLE
"Back"/"Undo" don't undo syntax extensions

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12575]
If you load a plugin such as, say, Ltac2 and then backtrack in CoqIDE, the syntax extensions from the plugin are not undone.  This causes unexpected and confusing errors when you try to redo those lines.

I ran into this while experimenting with Ltac2 Notation.  Here's an example in 8.12 from @tchajed:

```
(* evaluate these two lines, then delete the first and run the second *)
From Ltac2 Require Ltac2.
Ltac2 Eval ().
(* Error: Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/. *)
``` 

If you do the `Ltac2 Eval ()` in a fresh buffer, you get `Syntax error: illegal begin of vernac.`

From @ppedrot https://github.com/coq/coq/issues/11549#issuecomment-586730067:

> vernacular extensions should be backtracked upon by plugins. I wonder why nobody ever complained about that so far.

UPDATE: Backtracking seems to work correctly for both `Notation` and `Ltac2 Notation`, so apparently _some_ things are being backtracked.

**Comment by tchajed** [comment]
Excellent, thanks for putting this into an issue @jfehrle!

**Comment by jfehrle** [comment]
Stack trace, partly annotated, using 8.12 beta.  Not sure it tells us much.

```
Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.
Raised at file "clib/int.ml", line 39, characters 14-29
Called from file "clib/hMap.ml", line 361, characters 12-28
Called from file "user-contrib/Ltac2/tac2env.ml", line 220, characters 11-41  shortest_qualid_of_type
Called from file "user-contrib/Ltac2/tac2print.ml", line 68, characters 23-63
Called from file "user-contrib/Ltac2/tac2print.ml", line 76, characters 8-26
Called from file "user-contrib/Ltac2/tac2print.ml" (inlined), line 78, characters 22-46
Called from file "user-contrib/Ltac2/tac2entries.ml", line 823, characters 37-61  perform_eval
Called from file "vernac/vernacinterp.ml", line 45, characters 4-13  interp_typed_vernac VTReadProofOpt
Called from file "vernac/vernacinterp.ml", line 210, characters 20-60  interp_control
Called from file "lib/flags.ml", line 17, characters 14-17
Re-raised at file "clib/exninfo.ml", line 82, characters 4-38
Called from file "vernac/vernacinterp.ml", line 253, characters 18-43
Called from file "vernac/vernacinterp.ml", line 251, characters 6-279
Re-raised at file "clib/exninfo.ml", line 82, characters 4-38
Called from file "stm/stm.ml", line 2426, characters 16-43
Called from file "stm/stm.ml", line 1006, characters 6-10
Re-raised at file "clib/exninfo.ml", line 82, characters 4-38
Called from file "stm/stm.ml", line 2567, characters 4-105
Called from file "stm/stm.ml", line 2748, characters 4-60
Re-raised at file "clib/exninfo.ml", line 82, characters 4-38
Called from file "stm/stm.ml", line 2759, characters 12-50
Called from file "ide/idetop.ml", line 233, characters 13-28
Called from file "ide/idetop.ml", line 445, characters 12-15
Called from file "ide/protocol/xmlprotocol.ml", line 665, characters 29-46
```

**Comment by JasonGross** [comment]
Interestingly, I believe this used to be an issue with `Reserved Notation`.  That was fixed, and sometime later, custom entries were introduced, and I think this issue popped up when backtracking across custom entry creation.  I guess it was never discovered for plugin syntax extensions because, before Ltac2, plugins mostly didn't extend the syntax in ways that overlapped with existing syntax (though I wonder if you can hit a similar issue by backtracking across loading of ssreflect?), and in any case backtracking across the plugin that extended syntax was probably a relatively rare occurrence.

**Comment by jfehrle** [comment]
The CoqIDE behavior is confusing.  If I CTRL-up to the beginning of the file after the first try of executing the `Ltac2 Eval`, CoqIDE spawns a new worker process for the buffer, which won't ever have loaded Ltac2, so there's no anomaly and it correctly gives a syntax error the the `Ltac2 Eval`.

If I instead move the cursor to the beginning of the buffer and comment out the `From ... Require`, CoqIDE keeps the same worker process, so you get the anomaly.

The command entry for `Print Grammar vernac` is consistent with whether you get or don't get an anomaly.

**Comment by Zimmi48** [comment]
cc @coq/parsing-maintainers

**Comment by jfehrle** [comment]
@gares or @maximedenes:

I verified with a `printf` that `Stm.process_transaction` doesn't call `VCS.set_parsing_state` for a `From ... Require` command. Shouldn't it be doing that since the command can modify the parser?  If that seems right and you give me a little guidance, I'll prepare a PR.  (Of course I would not object if one of you submitted a fix yourself.)  Or if this is not the issue, perhaps you can suggest where to look next.

FWIW, another example that probably has the same root cause.  The following gets a syntax error on the `Ltac2 Notation` if the 2 lines are uncommented (and works correctly otherwise).

```
From Ltac2 Require Import Ltac2.
(*Back.
From Ltac2 Require Import Ltac2.*)
From Ltac2 Require Import Message.

Ltac2 Notation "ex" := print (of_string "x").
Goal True.
ex.
```

**Comment by gares** [comment]
IIRC set parsing state is called after each step, and the code seems to do that. This should be the line reached on commands such as Require: https://github.com/coq/coq/blob/master/stm/stm.ml#L2999 (since VernacRequire is classified as a Sideff with VtNow https://github.com/coq/coq/blob/master/stm/vernac_classifier.ml#L182).

I don't know if this is problem, but ML code cannot be unloaded and I'm pretty sure Ltac2 defines some parsing rules in ML (it must really). I'm pretty sure the "undoing" a regular notation works.

**Comment by herbelin** [comment]
With gramlib in the archive, its state could be registered to the global summary and I suspect this would solve the problem.

**Comment by jfehrle** [comment]
@gares That line is not executed for `From ... Require`.

```
                (* If execution has not been put in cache, we need to save the parsing state *)
                if (VCS.get_info id).state == EmptyState then begin
                try let _ = Sys.getenv("STM_INFO") in
                  Printf.printf "Call set_parsing_state at %d\n%!" __LINE__
                with Not_found -> ();
                VCS.set_parsing_state id parsing;
                end;
```

```
$ bin/coqtop
Welcome to Coq LAPTOP-LB5T3R83:/mnt/c/proj/coq,proof_state_info (0255d9592ba40d02c1c1ab5a27ebb1de5166ed9c)

Coq < From Ltac2 Require Import Ltac2.
[Loading ML file ltac2_plugin.cmxs ... done]

Coq < From Ltac2 Require Import Message.

Coq < Ltac2 Notation "ex" := print (of_string "x").
Goal True.
ex.
Coq < 1 subgoal

  ============================
  True

Unnamed_thm <
x

Unnamed_thm < Quit.
print stats
vcs state size = 946646 backup1 size = 946646 backup2 size = 28
jfehrle@LAPTOP-LB5T3R83:/mnt/c/proj/coq$ echo $STM_INFO
1
```

> I don't know if this is problem, but ML code cannot be unloaded

I don't see how that would be a problem for this use case.

> I'm pretty sure the "undoing" a regular notation works.

Yes, I tried undoing both regular notations and Ltac2 notations and it seemed to work correctly.  The Ltac2 code path looks a bit different from regular notations but I didn't investigate since it seems to work.

**Comment by ejgallego** [comment]
> With gramlib in the archive, its state could be registered to the global summary and I suspect this would solve the problem.

@herbelin even so that's a bit bizarre that pcoq already is not capturing this; maybe we could have a look at it in person some day?

**Comment by herbelin** [comment]
@ejgallego: you're right, these syntax extensions goes through `Pcoq.grammar_extend` which registers how to undo them when backtracking (even if this undoing is ad hoc, using `safe_delete_rule` rather than restoring a state as done in other places). So, why is this undoing not working?

**Comment by herbelin** [comment]
For reproducibility in `coqtop`, do:
```
From Ltac2 Require Ltac2.
Back 1.
Ltac2 Eval ().
```
The point is that `GRAMMAR EXTEND` rules are not (any more?) synchronized. According to `pcoq.mli` (comment on top of `grammar_extend`) this is on purpose. If I plug `GRAMMAR EXTEND` to the synchronization mechanism, this fixes the bug (see #13382). Not sure about what is the "right" thing to do.

**Comment by ejgallego** [comment]
See also https://github.com/coq/coq/issues/5234

**Comment by MSoegtropIMC** [comment]
@jfehrle : this appears to be fixed in CoqIDE 8.15, but not in VsCoq. Do you remember how this has been fixed?

**Comment by MSoegtropIMC** [comment]
Actually my older issue (https://github.com/coq/coq/issues/11793) is fixed, but this one appears to be not fixed.

**Comment by MSoegtropIMC** [comment]
More specifically what is fixed that stepping hence and forth over valid code including the Ltac2 require did not work in the past, but now it does. I find this more important than the error messages one gets when stepping over code which got invalid cause the Ltac2 require was removed.

**Comment by ejgallego** [comment]
I am positive we still have problems handling the state in the parsing engine, this should be IMHO a top priority in terms of engineering power.

**Comment by Blaisorblade** [comment]
A very similar issue is still present in CoqIDE as well. To reproduce on the following code:
```
From Coq Require Import Lia.
Require Import Ltac2.Ltac2.

Local Ltac2 lia_ltac1 () := ltac1:(lia).
Ltac2 Notation "lia2" := lia_ltac1 ().
```
Step to the end, delete a character to undo the require (say, the `.` at the end of `Require Import Ltac2.Ltac2.`), restore it, and step to the end again. That gives the following error on `"lia2"`:

```
Syntax error: [input_fun] expected after [binder] (in [tac2def_body]).
```

**Comment by SkySkimmer** [comment]
>A very similar issue is still present in CoqIDE as well. To reproduce on the following code:

Can't reproduce since 89ad33fb8de635766debe5d5bf8bd733aed028e4
Original example still reproduces in master

**Comment by SkySkimmer** [comment]
~~~coq
Require Import ssreflect.

Goal True.
  unfold idProp in |- *.
~~~
parses for me with whatever combination of executing then backtracking that I tried.

**Comment by ejgallego** [comment]
Actually this seems quite tricky to reproduce / minimize, let me research a bit more, as it seems the bug only happens with a very particular sequence of plugin loading / `freeze` calls.

**Comment by ejgallego** [comment]
The problem is pretty hard to debug due to all the hack in `ssr`, but here is a diff of `Print Grammar` and `Print Keywords` when things go good vs when they go bad:
```
--- r_right.txt	2023-01-03 20:11:56.617361667 +0100
+++ r_wrong.txt	2023-01-03 20:13:36.729364722 +0100
@@ -1975,7 +1975,7 @@
   | IDENT "swap"; int_or_var; int_or_var
   | IDENT "cycle"; int_or_var
   | IDENT "unshelve"; ltac_expr LEVEL "1"
-  | IDENT "transparent_abstract"; ltac_expr LEVEL "3"; "using"; ident
+  | IDENT "transparent_abstract"; ltac_expr LEVEL "3"; IDENT "using"; ident
   | IDENT "transparent_abstract"; ltac_expr LEVEL "3"
   | IDENT "destauto"; "in"; hyp
   | IDENT "destauto"
@@ -1986,9 +1986,9 @@
   | IDENT "specialize_eqs"; hyp
   | IDENT "generalize_eqs_vars"; hyp
   | IDENT "generalize_eqs"; hyp
-  | IDENT "stepr"; constr; "by"; tactic
+  | IDENT "stepr"; constr; IDENT "by"; tactic
   | IDENT "stepr"; constr
-  | IDENT "stepl"; constr; "by"; tactic
+  | IDENT "stepl"; constr; IDENT "by"; tactic
   | IDENT "stepl"; constr
   | IDENT "instantiate"; "("; ident; ":="; lconstr; ")"
   | IDENT "instantiate"; "("; natural; ":="; lconstr; ")"; hloc
@@ -1998,9 +1998,11 @@
   | IDENT "subst"
   | IDENT "notypeclasses"; IDENT "refine"; uconstr
   | IDENT "refine"; uconstr
-  | IDENT "autorewrite"; "*"; "with"; LIST1 preident; clause; "using"; tactic
+  | IDENT "autorewrite"; "*"; "with"; LIST1 preident; clause; IDENT "using";
+    tactic
   | IDENT "autorewrite"; "*"; "with"; LIST1 preident; clause
-  | IDENT "autorewrite"; "with"; LIST1 preident; clause; "using"; tactic
+  | IDENT "autorewrite"; "with"; LIST1 preident; clause; IDENT "using";
+    tactic
   | IDENT "autorewrite"; "with"; LIST1 preident; clause
   | IDENT "contradiction"; OPT constr_with_bindings
   | IDENT "decompose"; "["; LIST1 constr; "]"; constr
@@ -2689,7 +2691,6 @@
 ()
 )
 *
-**
 +
 ++
 ,
@@ -2698,12 +2699,10 @@
 .
 .(
 ..
-...
 /
 /\
 :
 ::
-::=
 ::>
 :=
 :>
@@ -2741,7 +2740,6 @@
 Type
 Variable
 [
-[=
 \/
 ]
 ^
@@ -2751,7 +2749,6 @@
 `{
 as
 at
-by
 cofix
 else
 end
@@ -2768,13 +2765,11 @@
 mod
 return
 then
-using
 where
 with
 {
 {|
 |
-|-
 ||
 }
 ~
```

So starting with a state with the ssrplugin loaded, then switching to a state before it was loaded, somehow the keywords and grammar rules are affected. So this bug may be specific to ssreflect actually.

**Comment by ejgallego** [comment]
cc @artagnon , here is the error you've been suffering.

**Comment by ppedrot** [comment]
Hmm, isn't the fix just to wrap the keyword declaration through `CLexer.set_keyword_state` in ssrvernac.mlg and g_ssrmatching.mlg into a dummy libobject using `Mltop.declare_cache_obj`? See e.g. the corresponding call in tac2entries.ml.

**Comment by ejgallego** [comment]
Thanks @ppedrot , I hope that works, the bug is very subtle and is giving me a headache (the dance done with the lexer and ssr_is_loaded is not very, ehem, pleasant)

I think the only way we can hope to have a reasonably maintainable setup is to do require writers to parsing and lexing state to grab a handle so they can update it functionally.

**Comment by SkySkimmer** [comment]
This may be related to calling `redo` in this remove_grammar code https://github.com/coq/coq/blob/6424bbc81e03447198784cf3dc56934a45145fdf/parsing/pcoq.ml#L169

**Comment by ejgallego** [comment]
See also https://github.com/coq/coq/issues/10146

**Comment by ejgallego** [comment]
> This may be related to calling `redo` in this remove_grammar code
> 
> https://github.com/coq/coq/blob/6424bbc81e03447198784cf3dc56934a45145fdf/parsing/pcoq.ml#L169

I think you may be into something @SkySkimmer , thanks; I can reproduce this better, and without involving ssreflect (still not a simple repro case yet).

So indeed, that happens with regular Coq plugins so seems like a core issue.

**Comment by SkySkimmer** [comment]
Definitely related as if I remove the redo code and test
~~~coq
Reserved Notation "& $ k" (at level 300).

Require Import Ltac2.Ltac2.

Ltac2 Eval ().
~~~
run everything, backtrack to before the Reserved Notation, run just Ltac2 Eval
then I get the expected `illegal begin of toplevel:vernac_toplevel.` (with master: uncaught Not_found)
(the Reserved Notation is needed because otherwise remove_grammar stops too early)

Turning this info into a fix is harder though.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/17069
