### ISSUE TITLE
Mac OS X CI builds fail at installing ruby

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12657]
```
==> Pouring adwaita-icon-theme-3.32.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/adwaita-icon-theme/3.32.0: 5,827 files, 22.6MB
Error: /usr/local/opt/ruby@2.6 is not a valid keg
```
https://github.com/coq/coq/pull/12556/checks?check_run_id=847065961

I also reported this at https://github.com/actions/virtual-environments/issues/1198, though it's possible this it just an issue with Coq's build script rather than the OSX build environment (maybe the homebrew commit is too old)?

**Comment by Zimmi48** [comment]
Let's indeed try to bump the pin to start with.

**Comment by Zimmi48** [comment]
FTR these errors are also happening on `v8.12`. I'm currently ignoring them to not block the backporting process but this should be solved ASAP.

**Comment by Zimmi48** [comment]
Bumping seems to do the trick: the macOS build for #12672 has passed the previously failing step.

**Comment by ejgallego** [comment]
This is still a problem , let's hope we can fix it in the next release.
