### ISSUE TITLE
Anomaly. Universe undefined

### ISSUE THREAD

**Issue by Columbus240** [coq/coq#14440]
#### Description of the problem
In Coq v8.13.2 and the current development branch, the following gives an anomaly.
The example is not yet minimized, because it also triggered a problem in find-bug.py (JasonGross/coq-tools#61).

@coqbot: minimize
```
opam install -y coq-ext-lib
eval $(opam env)
git clone --depth 1 -b SCNT https://github.com/Columbus240/category-theory
cd category-theory
make -j2 Structure/Cone/Natural/Transformation.vo
```

**Comment by Columbus240** [comment]
Using find-bug.py I could reduce it to the following, but maybe it could be reduced further. Still reproduces with v8.13.2 and commit d41ade89ae.
```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-w" "-deprecated-native-compiler-option" "-R" "." "Category" "-top" "Transformation" "-R" "." "Top" "-native-compiler" "ondemand" "-native-compiler" "ondemand") -*- *)
(* coqc version 8.14+alpha compiled with OCaml 4.10.0
   coqtop version 8.14+alpha *)
Axiom proof_admitted : False.
Tactic Notation "admit" := abstract case proof_admitted.
Require Coq.Program.Program.
Export Coq.Program.Program.

Close Scope nat_scope.
Declare Scope category_theory_scope.
Open Scope category_theory_scope.
Export Coq.Classes.CMorphisms.

Generalizable All Variables.

Notation "∀  x .. y , P" := (forall x, .. (forall y, P) ..)
  (at level 200, x binder, y binder, right associativity) :
  category_theory_scope.
Notation "x ↔ y" := (iffT x y)
  (at level 95, no associativity) : category_theory_scope.

Infix "∧" := prod (at level 80, right associativity) : category_theory_scope.

Class Setoid A := {
  equiv : crelation A;
  setoid_equiv :> Equivalence equiv
}.

Notation "f ≈ g" := (equiv f g) (at level 79) : category_theory_scope.

Program Instance setoid_refl `(sa : Setoid A) :
  Reflexive equiv.
Obligation 1.
admit.
Defined.

Program Instance setoid_sym `(sa : Setoid A) :
  Symmetric equiv.
Obligation 1.
admit.
Defined.

Program Instance setoid_trans `(sa : Setoid A) :
  Transitive equiv.
Obligation 1.
admit.
Defined.
Import Coq.Bool.Bool.

Open Scope lazy_bool_scope.

Ltac simplify :=
  repeat
    (match goal with
     | [ H : _ ∧ _ |- _ ] =>
       let H' := fresh "H" in destruct H as [H H']
     | [ |- _ ∧ _ ] => split

     | [ H : _ /\ _ |- _ ] =>
       let H' := fresh "H" in destruct H as [H H']
     | [ |- _ /\ _ ] => split

     | [ H : _ ↔ _ |- _ ] =>
       let H' := fresh "H" in destruct H as [H H']
     | [ |- _ ↔ _ ] => split

     | [ H : (_, _) = (_, _) |- _ ] => inversion_clear H

     | [ H : _ * _ |- _ ] =>
       let x := fresh "x" in
       let y := fresh "y" in
       destruct H as [x y]
     | [ |- _ * _ ] => split

     | [ H : { _ : _ & _ } |- _ ] =>
       let x := fresh "x" in
       let e := fresh "e" in
       destruct H as [x e]
     | [ |- { _ : _ & _ } ] =>
       unshelve (refine (existT _ _ _))
     end; intros).

Ltac cat :=
  simplify;
  autorewrite with categories;
  auto with category_laws;
  try reflexivity.
Hint Extern 6 (equiv ?X ?Y) =>
  apply Equivalence_Symmetric : category_laws.

Ltac cat_simpl :=
  program_simpl; autounfold;
  try solve [
    repeat match goal with
    | [ |- Equivalence _ ] => constructor; repeat intro; simpl; try cat; intuition
    | [ |- Proper _ _ ] => repeat intro; simpl; try cat; intuition
    | [ |- respectful _ _ _ _ ] => repeat intro; simpl; try cat; intuition
    end;
    program_simpl; autounfold in *;
    simpl in *; intros; simplify;
    simpl in *; cat];
  simpl in *.

Global Obligation Tactic := cat_simpl.

Reserved Infix "~>" (at level 90, right associativity).

Class Category := {
  obj : Type;

  uhom := Type : Type;
  hom : obj -> obj -> uhom where "a ~> b" := (hom a b);
  homset :> ∀ X Y, Setoid (X ~> Y);

  id {x} : x ~> x;
  compose {x y z} (f: y ~> z) (g : x ~> y) : x ~> z
    where "f ∘ g" := (compose f g);

  compose_respects x y z :>
    Proper (equiv ==> equiv ==> equiv) (@compose x y z);

  dom {x y} (f: x ~> y) := x;
  cod {x y} (f: x ~> y) := y;

  id_left  {x y} (f : x ~> y) : id ∘ f ≈ f;
  id_right {x y} (f : x ~> y) : f ∘ id ≈ f;

  comp_assoc {x y z w} (f : z ~> w) (g : y ~> z) (h : x ~> y) :
    f ∘ (g ∘ h) ≈ (f ∘ g) ∘ h;
}.

Delimit Scope category_scope with category.
Delimit Scope object_scope with object.
Delimit Scope morphism_scope with morphism.

Notation "x ~> y" := (@hom _%category x%object y%object)
  (at level 90, right associativity) : homset_scope.
Notation "x ~{ C }~> y" := (@hom C%category x%object y%object)
  (at level 90) : homset_scope.

Notation "id[ x ]" := (@id _%category x%object)
  (at level 9, format "id[ x ]") : morphism_scope.

Notation "f ∘ g" :=
  (@compose _%category _%object _%object _%object f%morphism g%morphism)
  : morphism_scope.

Coercion obj : Category >-> Sortclass.

Hint Rewrite @id_left : categories.
Hint Rewrite @id_right : categories.

Open Scope category_scope.
Open Scope homset_scope.
Open Scope morphism_scope.

Hint Extern 10 (?X ∘ (?Y ∘ ?Z) ≈ ?W) =>
  rewrite <- comp_assoc; cat : category_laws.

Section Isomorphism.

Context {C : Category}.

Class Isomorphism (x y : C) : Type := {
  to   : x ~> y;
  from : y ~> x;
}.

Arguments to {x y} _.
Arguments from {x y} _.

Infix "≅" := Isomorphism (at level 91) : category_scope.

End Isomorphism.

Declare Scope isomorphism_scope.
Open Scope isomorphism_scope.

Notation "x ≅ y" := (@Isomorphism _%category x%object y%object)
  (at level 91) : isomorphism_scope.

Arguments to {_%category x%object y%object} _%morphism.
Arguments from {_%category x%object y%object} _%morphism.

Class Functor {C D : Category} := {
  fobj : C -> D;
  fmap {x y : C} (f : x ~> y) : fobj x ~> fobj y;

  fmap_respects :> ∀ x y, Proper (equiv ==> equiv) (@fmap x y);

  fmap_id {x : C} : fmap (@id C x) ≈ id;
  fmap_comp {x y z : C} (f : y ~> z) (g : x ~> y) :
    fmap (f ∘ g) ≈ fmap f ∘ fmap g
}.
Declare Scope functor_type_scope.
Delimit Scope functor_scope with functor.
Open Scope functor_type_scope.

Coercion fobj : Functor >-> Funclass.

Notation "C ⟶ D" := (@Functor C%category D%category)
  (at level 90, right associativity) : functor_type_scope.
Notation "fmap[ F ]" := (@fmap _ _ F%functor _ _)
  (at level 9, format "fmap[ F ]") : morphism_scope.

Hint Rewrite @fmap_id : categories.

Program Instance Functor_Setoid {C D : Category} : Setoid (C ⟶ D) := {
  equiv := fun F G =>

    { iso : ∀ x : C, F x ≅ G x
    & ∀ (x y : C) (f : x ~> y),
        fmap[F] f ≈ from (iso y) ∘ fmap[G] f ∘ to (iso x) }
}.
Next Obligation.
admit.
Defined.

Program Definition Compose
        {C : Category} {D : Category} {E : Category}
        (F : D ⟶ E) (G : C ⟶ D) : C ⟶ E := {|
  fobj := fun x => fobj (fobj x);
  fmap := fun _ _ f => fmap (fmap f)
|}.
Next Obligation.
admit.
Defined.
Next Obligation.
admit.
Defined.

Notation "F ◯ G" := (Compose F%functor G%functor)
  (at level 40, left associativity) : category_scope.

Section Transform.

Context {C : Category}.
Context {D : Category}.
Context {F : C ⟶ D}.
Context {G : C ⟶ D}.

Class Transform := {
  transform {x} : F x ~> G x;

  naturality {x y} (f : x ~> y) :
    fmap[G] f ∘ transform ≈ transform ∘ fmap[F] f;
}.

End Transform.

Arguments transform {_ _ _ _} _ _.
Declare Scope transform_type_scope.
Delimit Scope transform_scope with transform.
Open Scope transform_type_scope.

Notation "F ⟹ G" := (@Transform _ _ F%functor G%functor)
  (at level 90, right associativity) : transform_type_scope.

Notation "transform[ F ]" := (@transform _ _ _ _ F%transform)
  (at level 9, only parsing, format "transform[ F ]") : morphism_scope.
Notation "naturality[ F ]" := (@naturality _ _ _ _ F%transform)
  (at level 9, only parsing, format "naturality[ F ]") : morphism_scope.

Coercion transform : Transform >-> Funclass.

Ltac transform :=
  unshelve (refine {| transform := _ |}; simpl; intros).

Program Definition whisker_left {C D : Category}
        {E : Category} (X : D ⟶ E)
        {F G : C ⟶ D} `(N : F ⟹ G) : X ◯ F ⟹ X ◯ G := {|
  transform := fun x => fmap[X] (N x)
|}.
Next Obligation.
admit.
Defined.

Section Fun.

Context {C : Category}.
Context {D : Category}.

Program Definition nat_equiv {F : C ⟶ D} {G : C ⟶ D} : crelation (F ⟹ G) :=
  fun n m => ∀ A, transform[n] A ≈ transform[m] A.

Hint Unfold nat_equiv : core.

Global Program Definition nat_equiv_equivalence {F : C ⟶ D} {G : C ⟶ D} :
  Equivalence (@nat_equiv F G).
admit.
Defined.

Global Program Instance nat_Setoid {F : C ⟶ D} {G : C ⟶ D} :
  Setoid (F ⟹ G) := {
  equiv := nat_equiv;
  setoid_equiv := nat_equiv_equivalence
}.

Global Program Definition nat_id {F : C ⟶ D} : F ⟹ F := {|
  transform := fun X => fmap (@id C X)
|}.

Global Program Definition nat_compose {F : C ⟶ D} {G : C ⟶ D} {K : C ⟶ D}
  (f : G ⟹ K) (g : F ⟹ G) : F ⟹ K := {|
  transform := fun X => transform[f] X ∘ transform[g] X
|}.
Next Obligation.
admit.
Defined.

Global Program Definition nat_compose_respects
       {F : C ⟶ D} {G : C ⟶ D} {K : C ⟶ D} :
  Proper (equiv ==> equiv ==> equiv) (@nat_compose F G K).
admit.
Defined.

Global Program Definition Fun : Category := {|
  obj     := C ⟶ D;
  hom     := @Transform C D;
  id      := @nat_id;
  compose := @nat_compose;

  compose_respects := @nat_compose_respects
|}.

End Fun.

Notation "[ C , D ]" := (@Fun C D)
  (at level 90, right associativity, format "[ C ,  D ]") : category_scope.
Hint Unfold nat_equiv : core.
Set Universe Polymorphism.

Program Instance Diagonal {C : Category} (J : Category) : C ⟶ [J, C] := {
  fobj := fun x =>
    {| fobj := fun _ => x
     ; fmap := fun _ _ _ => id[x] |};
  fmap := fun _ _ f =>
    {| transform := fun _ => f |}
}.

Class Cone `(F : J ⟶ C) := {
  vertex_obj : C;
  vertex_map {x : J} : vertex_obj ~{C}~> F x;

  ump_cones {x y : J} (f : x ~{J}~> y) :
    fmap[F] f ∘ @vertex_map x ≈ @vertex_map y
}.

Theorem Cone_Transform {J : Category} {C : Category} (F : J ⟶ C) (d : C) :
  Diagonal J d ⟹ F ↔ { c : Cone F | vertex_obj = d }.
Proof.
  split; intros.
  -
 unshelve eexists.
    +
 unshelve econstructor; intros.
      *
 exact d.
      *
 apply X.
      *
 simpl.
        rewrite (naturality[X]); cat.
    +
 reflexivity.
  -
 transform; simpl; intros;
    destruct X; subst.
    +
 apply x0.
    +
 cat; apply ump_cones.
Qed.
```

**Comment by SkySkimmer** [comment]
Simplified end of the test:
~~~coq
Class Cone `(F : J ⟶ C) := {
  vertex_obj : C;
}.

Theorem Cone_Transform {J : Category} {C : Category} (F : J ⟶ C) (d : C) :
  { c : Cone F | vertex_obj = d } -> Diagonal J d ⟹ F.
Proof.
 intros; transform; intros; destruct X.

 - subst. admit.
 - subst. admit.
Qed.
~~~
Something is going on with the 2nd subst which is only triggered when the first one is also present.

**Comment by SkySkimmer** [comment]
Also present in 8.11.2.

**Comment by Columbus240** [comment]
I managed to reduce it some more:
```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-w" "-deprecated-native-compiler-option" "-R" "." "Top" "-top" "SCNT" "-native-compiler" "ondemand" "-native-compiler" "ondemand") -*- *)
(* coqc version 8.13.2 (April 2021) compiled on Apr 27 2021 6:37:37 with OCaml 4.09.0
   coqtop version 8.13.2 (April 2021) *)
Axiom proof_admitted : False.
Tactic Notation "admit" := abstract case proof_admitted.
Require Coq.Program.Program.
Export Coq.Program.Program.
Export Coq.Classes.CMorphisms.

Notation "∀  x .. y , P" := (forall x, .. (forall y, P) ..)
  (at level 200, x binder, y binder, right associativity).

Class Setoid A := {
  equiv : crelation A;
  setoid_equiv :> Equivalence equiv
}.

Notation "f ≈ g" := (equiv f g) (at level 79).

Reserved Infix "~>" (at level 90, right associativity).

Class Category := {
  obj : Type;

  uhom := Type : Type;
  hom : obj -> obj -> uhom where "a ~> b" := (hom a b);
  homset :> ∀ X Y, Setoid (X ~> Y);

  compose {x y z} (f: y ~> z) (g : x ~> y) : x ~> z
    where "f ∘ g" := (compose f g);
}.

Notation "x ~> y" := (@hom _ x y)
  (at level 90, right associativity).

Notation "f ∘ g" :=
  (@compose _ _ _ _ f g).

Coercion obj : Category >-> Sortclass.

Class Functor (C D : Category) := {
  fobj : C -> D;
  fmap {x y : C} (f : x ~> y) : fobj x ~> fobj y;
}.

Coercion fobj : Functor >-> Funclass.

Notation "fmap[ F ]" := (@fmap _ _ F _ _)
  (at level 9, format "fmap[ F ]").

Class Transform {C D : Category} (F G : Functor C D) := {
  transform {x} : F x ~> G x;

  naturality {x y} (f : x ~> y) :
    fmap[G] f ∘ transform ≈ transform ∘ fmap[F] f;
}.

Ltac transform :=
  unshelve (refine {| transform := _ |}; simpl; intros).

Global Program Definition Fun (C D : Category) : Category := {|
  obj     := Functor C D;
  hom     := @Transform C D;
|}.
Admit Obligations.

Program Instance Diagonal {C : Category} (J : Category) : Functor C (Fun J C) := {
  fobj := fun x =>
    {| fobj := fun _ => x
     ; fmap := fun _ _ _ => _ |};
  fmap := fun _ _ f =>
    {| transform := fun _ => f |}
}.
Admit Obligations.

Class Cone {J C : Category} (F : Functor J C) := {
  vertex_obj : C;
}.

Set Universe Polymorphism.

Theorem Cone_Transform {J : Category} {C : Category} (F : Functor J C) (d : C) :
  { c : Cone F | vertex_obj = d } -> Transform (Diagonal J d) F.
Proof.
 intros; transform; intros; destruct X.
 - subst. admit.
 - subst. admit.
Qed.
```

**Comment by ppedrot** [comment]
A version without external Require:
```
Axiom proof_admitted : False.
Ltac admit := case proof_admitted.

Set Universe Polymorphism.

Definition crelation@{u v} (A : Type@{u}) := A -> A -> Type@{v}.

Unset Universe Polymorphism.

Class Setoid A := { equiv : crelation A; }.

Class Category := {
  obj : Type;

  uhom := Type : Type;
  hom : obj -> obj -> uhom;
  homset :> forall X Y, Setoid (hom X Y);

  compose {x y z} (f: hom y z) (g : hom x y) : hom x z
}.

Notation "x ~> y" := (@hom _ x y) (at level 90, right associativity).
Notation "f ∘ g" := (@compose _ _ _ _ f g) (at level 40, left associativity).

Coercion obj : Category >-> Sortclass.

Record Functor (C D : Category) := {
  fobj : C -> D;
  fmap {x y : C} (f : x ~> y) : fobj x ~> fobj y;
}.

Coercion fobj : Functor >-> Funclass.

Notation "fmap[ F ]" := (@fmap _ _ F _ _)
  (at level 9, format "fmap[ F ]").

Record Transform {C D : Category} (F G : Functor C D) := {
  transform {x} : F x ~> G x;

  naturality {x y} (f : x ~> y) :
    equiv (fmap[G] f ∘ transform) (transform ∘ fmap[F] f);
}.

Ltac transform :=
  unshelve (refine {| transform := _ |}; simpl; intros).

Definition Fun (C D : Category) : Category.
Proof.
refine ({|
  obj     := Functor C D;
  hom     := @Transform C D;
|}).
+ admit.
+ admit.
Defined.

Definition Diagonal {C : Category} (J : Category) : Functor C (Fun J C).
Proof.
simple refine
({|
  fobj := fun x => _;
  fmap := fun _ _ f => _;
|}).
+ refine ({| fobj := fun _ => x; fmap := fun _ _ _ => _ |}).
  admit.
+ simple refine ({| transform := fun _ => _ |}).
  - refine f.
  - admit.
Defined.

Record Cone (C : Category) := { vertex_obj : C }.

Set Universe Polymorphism.

Theorem Cone_Transform {J : Category} {C : Category} (F : Functor J C) (d : C) :
  { c : Cone C | @vertex_obj _ c = d } -> Transform (Diagonal J d) F.
Proof.
 intros; transform; intros; destruct X.
 - subst. admit.
 - subst. admit.
Qed.
```

**Comment by Columbus240** [comment]
I degenerated it a bit further:
```coq
Set Implicit Arguments.
Axiom proof_admitted : False.
Ltac admit := case proof_admitted.

Class Category := {
  obj : Type;

  uhom := Type : Type;
  hom : obj -> obj -> uhom;
  homset : forall (X Y : obj), hom X Y -> hom X Y -> Type;

  compose {x y z} (f: hom y z) (g : hom x y) : hom x z
}.

Notation "x ~> y" := (@hom _ x y) (at level 90, right associativity).
Notation "f ∘ g" := (@compose _ _ _ _ f g) (at level 40, left associativity).

Coercion obj : Category >-> Sortclass.

Record Functor (C D : Category) := {
  fobj : C -> D;
  fmap {x y : C} (f : x ~> y) : fobj x ~> fobj y;
}.

Notation "fmap[ F ]" := (@fmap _ _ F _ _)
  (at level 9, format "fmap[ F ]").

Record Transform {C : Category} (F G : Functor C C) := {
  transform {x} : (fobj F x) ~> (fobj G x);

  naturality {x y} (f : x ~> y) :
    homset _ _ (fmap[G] f ∘ transform) (transform ∘ fmap[F] f);
}.

Definition Fun (C : Category) : Category.
Proof.
refine ({|
  obj     := Functor C C;
  hom     := @Transform C;
|}).
+ admit.
+ admit.
Defined.

Definition Diagonal (C : Category) : Functor C (Fun C).
Proof.
  admit.
Defined.

Set Universe Polymorphism.

Theorem Cone_Transform {C : Category} (F : Functor C C) (d : C) :
  { c : { x : C | True } | proj1_sig c = d } -> Transform (fobj (Diagonal C) d) F.
Proof.
  intros;
    unshelve (refine {| transform := _ |}; simpl; intros);
    intros; destruct X.
  - subst. admit.
  - subst. admit.
Qed.
```
Strangely, replacing the term `{ c : Cone C | _ }` in the theorem with `{ c : C | c = d }`, the `internal_eq_rew_dep` term is missing and the anomaly doesn’t arise. In this case, the LHS of the equation `c = d` doesn’t appear in the goal-term, so rewriting/substituting is a no-op.

I tried replacing the term `Transform _ _` of the theorem with some simple sigma-types, but didn’t manage to reproduce the anomaly.

Should `subst` even generate the `internal_eq_rew_dep` term? If it wouldn’t the problem wouldn’t arise. Or is it better, if the universe-handling related to `internal_eq_rew_dep` is improved? I think that’s where I currently know too little to help.

**Comment by Columbus240** [comment]
I minimized it further. It’s possible to replace all occurrences of `obj` by `Type` and preserve the error. I noticed, that the error doesn’t appear in v8.8.2.

```coq
Set Implicit Arguments.
Axiom proof_admitted : False.
Ltac admit := case proof_admitted.

Variable (obj : Type)
         (hom : obj -> obj -> Type)
         (homset : forall (X Y : obj), hom X Y -> hom X Y -> Type).

Notation "x ~> y" := (@hom x y) (at level 90, right associativity).

Record Functor := {
  fobj : obj -> obj;
  fmap {x y : obj} (f : x ~> y) : fobj x ~> fobj y;
}.

Record Transform (F : Functor) := {
  transform {x} : (fobj F x) ~> (fobj F x);

  naturality {x y} (f : x ~> y) :
    homset (@transform x) (@transform x);
}.

Variable Diagonal : obj -> Functor.

Set Universe Polymorphism.

Theorem Cone_Transform (F : Functor) (d : obj) :
  { c : { x : obj | True } | proj1_sig c = d } -> Transform (Diagonal d).
Proof.
  intros;
    unshelve (refine {| transform := _ |}; simpl; intros);
    intros; destruct X.
  - subst. admit.
  - subst. admit.
Qed.
```

**Comment by mrhaandi** [comment]
Further minimized (still broken on `master` between 8.16 and 8.17) :
```coq
Axioms
  (P : unit -> Type)
  (P_intro : forall u, P u)
  (Q : forall u, P u -> Type) 
  (* Q : forall u, P u -> Prop 
     gives Anomaly
     "File "kernel/term_typing.ml", line 278, characters 7-13: Assertion failed." *)
  (Q_intro : forall u, Q u (P_intro u)).

Set Universe Polymorphism.

Lemma broken (c d : unit) (E : c = d) :
  Q d (eq_rect c P (P_intro c) d E).
Proof.
  subst d. exact (Q_intro c).
Qed. (* Anomaly "in Univ.repr: Universe Test.441 undefined." *)
```

Changing `Type` to `Prop` changes the anomaly to `"File "kernel/term_typing.ml", line 278, characters 7-13: Assertion failed."`.
https://github.com/coq/coq/blob/6bd2d5a80a8b9930e1989ec6c53b22510a3583ec/kernel/term_typing.ml#L278

**Comment by ppedrot** [comment]
This particular bug is fixed as of 456afe79681432fa74f2f29421649adfab934341 but I'm not sure we cannot replay it using abstract rather than the implicit scheme creation triggered by rewrite that was subtly and recently removed.

**Comment by SkySkimmer** [comment]
I don"t think we can reproduce using abstract because the problem seems related to subst producing a univ monomorphic scheme during a univ poly proof. Abstract should always have the same mono/poly mode as the current proof.

**Comment by SkySkimmer** [comment]
(the implicit scheme creation is still there but deprecated, and the schemes for eq have been predeclared. If we make a -noinit version of the bug we will still see the issue)
