### ISSUE TITLE
"coqide -config" completely broken

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15816]
**On windows** If I run `coqide -config` in 8.15.0, an empty window appears.  After perhaps a minute, the top menu appears and I see this message at the bottom of the panel, at which time the menu and toolbar appear with no `*scratch*` buffer.  If I try to create a new buffer, the GUI hangs.  Same thing for `-where`, though `-help` works as it should.

![image](https://user-images.githubusercontent.com/1253341/156874891-12b6caf6-7e0b-42a5-b447-2a04df166828.png)

**On Linux** `dune exec -- dev/shim/coqide-prelude -config` on opens a window for about 1/10 of a second, then exits without printing anything.  If I add a several second loop at the end of `Coqinit.print_query`, I see following all at once.  If I change the `Envars.print_config stdout` to go to stderr, I see the right thing on my console.

![image](https://user-images.githubusercontent.com/1253341/156874470-f56668b6-c36c-4a32-ab79-b8aadd6bd4b3.png)
![image](https://user-images.githubusercontent.com/1253341/156874500-c37db51d-3c23-4de5-9c01-bdd327dfa885.png)
![image](https://user-images.githubusercontent.com/1253341/156874514-ee2706e6-02be-4921-b723-025779f7741d.png)
![image](https://user-images.githubusercontent.com/1253341/156874518-a691cdff-8c94-4fc6-bf31-51e4f7492ba4.png)
![image](https://user-images.githubusercontent.com/1253341/156874526-e114a2f2-c462-42b6-99ab-811131fc86b8.png)
![image](https://user-images.githubusercontent.com/1253341/156874537-6fdf8bec-2632-4391-81ee-449524e38686.png)
![image](https://user-images.githubusercontent.com/1253341/156874547-ebc913c5-73a6-47f4-b3b3-727b71b7bbce.png)

**Comment by Frigory33** [comment]
Hello. This bug is fixed, isn’t it? `dune exec -- dev/shim/coqide -config`, with the master branch, works correctly on my machine (I’m using Manjaro Linux).

However, with the version installed on my system (8.16.1), `coqide -config` crashes with error code 248.

**Comment by jfehrle** [comment]
No, still the same problem in master (on Windows/WSL with Ubuntu).

**Comment by Frigory33** [comment]
OK. For me, it doesn’t work with `coqide -where` even on master.

I’ll see if I can improve this. Note that you can still use another command such as `coqc -config` to get that kind of info (CoqIDE uses `coqidetop.opt`, which seems to work correctly).
