### ISSUE TITLE
Strange typeclass resolution failure: Cannot unify <term> and <identical term>

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#17688]
#### Description of the problem

We are seeing a strange typeclass resolution failure in Iris. We managed to reproduce it in Iris itself (it originally came up further downstream) but I have no idea how to further minimize this. You can find a reproducer in the Iris repo (https://gitlab.mpi-sws.org/iris/iris.git) in branch `coq-bugs/tc-resolution-cannot-unify-with-self` in file `iris/base_logic/lib/gen_heap.v` ([link to code](https://gitlab.mpi-sws.org/iris/iris/-/blob/coq-bugs/tc-resolution-cannot-unify-with-self/iris/base_logic/lib/gen_heap.v#L200); the lemma being applied is [this](https://gitlab.mpi-sws.org/iris/iris/-/blob/coq-bugs/tc-resolution-cannot-unify-with-self/iris/bi/lib/fractional.v#L198)).

In the typeclass trace, we have it trying to solve
```
Debug: Launching resolution fixpoint on 2 goals:
?X827 : (AsFractional (l ↦{#q1} v) ?b q1)
?X828 : (AsFractional (l ↦{#q2} v) ?b q2)
```
This should be trivial with the following instance
```
  Global Instance mapsto_as_fractional l q v :
    AsFractional (l ↦{#q} v) (λ q, l ↦{#q} v)%I q.
```
However, instead we get
```
Debug: 1: looking for (AsFractional (l ↦{#q1} v) ?b q1) with backtracking
Debug: 1.1: simple apply mapsto_as_fractional on
(AsFractional (l ↦{#q1} v) ?b q1) failed with: Cannot unify (λ q : Qp, (l ↦{#q} v)%I) and 
(λ q : Qp, (l ↦{#q} v)%I)
```
Even with `Set Printing All`, this is the same term twice: it cannot unify a term with itself?!? And why does it even try to do that, it should be unifying `?b` with `(λ q : Qp, (l ↦{#q} v)%I`? (The *second* goal needs to then apply `mapsto_as_fractional` again and then it will have this exact unification problem, but we aren't even getting there. This is the first application of `mapsto_as_fractional`.)

If I remove the `Typeclasses Opaque mapsto.`, the error goes away. (`mapsto` is what the `↦` expands to.) But `mapsto` should not be unfolded for this typeclass problem so this makes little sense (and some definitions we really need to be opaque for performance reasons).

If I try to reconstruct the same TC problem manually, then it doesn't fail:
```
Lemma test l q1 q2 v : ∃ (Φ : Qp → _),
  TCAnd (AsFractional (l ↦{#q1} v) Φ q1) (AsFractional (l ↦{#q2} v) Φ q2).
Proof. eexists. apply _. Qed.
```
So looks like there is some other magic TC resolution state that is relevant.

Adding `Hint Extern 5 (AsFractional _ _ _) => simple apply mapsto_as_fractional : typeclass_instances.` also fixes the issue, so this is another instance of the TC trace giving misleading information about the tactics being run (Cc https://github.com/coq/coq/issues/17562).

Cc @robbertkrebbers 

#### Coq Version

8.17.0

**Comment by Janno** [comment]
Unfortunately the unification trace does not reveal anything useful:

```
[tactic-unification] Starting unification: @AsFractional (uPredI (iResUR Σ))
                                             (@mapsto L EqDecision0 H V Σ gen_heapGS0 ?M12359 (DfracOwn ?M12360) ?M12361)
                                             (fun q : Qp => @mapsto L EqDecision0 H V Σ gen_heapGS0 ?M12359 (DfracOwn q) ?M12361)
                                             ?M12360 ~= @AsFractional (uPredI (iResUR Σ))
                                                          (@mapsto L EqDecision0 H V Σ gen_heapGS0 l (DfracOwn q1) v) 
                                                          ?b q1
Debug:
[tactic-unification] @AsFractional (uPredI (iResUR Σ)) (@mapsto L EqDecision0 H V Σ gen_heapGS0 ?M12359 (DfracOwn ?M12360) ?M12361)
                       (fun q : Qp => @mapsto L EqDecision0 H V Σ gen_heapGS0 ?M12359 (DfracOwn q) ?M12361) 
                       ?M12360 ~= @AsFractional (uPredI (iResUR Σ)) (@mapsto L EqDecision0 H V Σ gen_heapGS0 l (DfracOwn q1) v) ?b q1
Debug: [tactic-unification] @AsFractional ~= @AsFractional
Debug: [tactic-unification] uPredI (iResUR Σ) ~= uPredI (iResUR Σ)
Debug: [tactic-unification] uPredI ~= uPredI
Debug: [tactic-unification] iResUR Σ ~= iResUR Σ
Debug: [tactic-unification] iResUR ~= iResUR
Debug: [tactic-unification] Σ ~= Σ
Debug:
[tactic-unification] @mapsto L EqDecision0 H V Σ gen_heapGS0 ?M12359 (DfracOwn ?M12360) ?M12361 ~= @mapsto L EqDecision0 H V Σ
                                                                                                     gen_heapGS0 l 
                                                                                                     (DfracOwn q1) v
Debug: [tactic-unification] @mapsto ~= @mapsto
Debug: [tactic-unification] L ~= L
Debug: [tactic-unification] EqDecision0 ~= EqDecision0
Debug: [tactic-unification] H ~= H
Debug: [tactic-unification] V ~= V
Debug: [tactic-unification] Σ ~= Σ
Debug: [tactic-unification] gen_heapGS0 ~= gen_heapGS0
Debug: [tactic-unification] ?M12359 ~= l
Debug: [tactic-unification] DfracOwn ?M12360 ~= DfracOwn q1
Debug: [tactic-unification] DfracOwn ~= DfracOwn
Debug: [tactic-unification] ?M12360 ~= q1
Debug: [tactic-unification] ?M12361 ~= v
Debug: [tactic-unification] fun q : Qp => @mapsto L EqDecision0 H V Σ gen_heapGS0 ?M12359 (DfracOwn q) ?M12361 ~= ?b
Debug: [tactic-unification] ?M12360 ~= q1
Debug: [tactic-unification] Leaving unification with success
Debug: 1.1: simple apply mapsto_as_fractional on
(@AsFractional (uPredI (iResUR Σ)) (@mapsto L EqDecision0 H V Σ gen_heapGS0 l (DfracOwn q1) v) ?b q1) failed with: Cannot unify 
(fun q : Qp => @mapsto L EqDecision0 H V Σ gen_heapGS0 l (DfracOwn q) v) and (fun q : Qp =>
                                                                              @mapsto L EqDecision0 H V Σ gen_heapGS0 l 
                                                                                (DfracOwn q) v)
```


> Adding `Hint Extern 5 (AsFractional _ _ _) => simple apply mapsto_as_fractional : typeclass_instances.` also fixes the issue, so this is another instance of the TC trace giving misleading information about the tactics being run (Cc #17562).

The closest tactic to typeclass search is `autoapply` but it doesn't seem close enough to replicate whatever is happening here. If I add 
```
Hint Extern 5 (AsFractional _ _ _) => autoapply @mapsto_as_fractional with typeclass_instances : typeclass_instances.
```
Then I only get a single unification trace entry:

```
1: looking for (@AsFractional (uPredI (iResUR Σ)) (@mapsto L EqDecision0 H V Σ gen_heapGS0 l (DfracOwn q1) v) ?b q1) with backtracking
Debug: [unification] Heuristic:
                              ?b q
                              @unseal _ _ (@mapsto_aux L EqDecision0 H V Σ gen_heapGS0) l (DfracOwn q) v
Debug: 1.1: (*external*) autoapply mapsto_as_fractional with typeclass_instances on
(@AsFractional (uPredI (iResUR Σ)) (@mapsto L EqDecision0 H V Σ gen_heapGS0 l (DfracOwn q1) v) ?b q1) failed with: Cannot unify 
(?b q) and (@unseal _ _ (@mapsto_aux L EqDecision0 H V Σ gen_heapGS0) l (DfracOwn q) v)
```

What's interesting is that `mapsto` has been expanded to `unseal .. (maptso_aux ..)`. Maybe this unification heuristic step is allowed to pierce TC opaque terms and then stumbles over itself when it tries to justify the unfolding heuristic by actually unifying the two sides (which cannot work because opacity settings forbid it)?

**Comment by SkySkimmer** [comment]
The TC debug has "cannot unify" but the unification debug has no corresponding "failure" message?
Maybe it's failing in new unification (`Set Debug "unification"`)?

**Comment by SkySkimmer** [comment]
If you `Set Debug "backtrace"` the debug `Cannot unify` may also have backtrace info on it (not sure)

**Comment by Blaisorblade** [comment]
- I recommend _adding_ `Set Debug "all" to `Typeclasses Debug`. `unification`, `tactic-unification` _and_ `RAKAM` all show up. Log in https://gist.github.com/Blaisorblade/f74742d5474bc873140fb1236c02cf3c.

- To reduce noise and help the dnet skip extra attempts I made extra things opaque t— `Typeclasses Opaque ghost_map_auth.` and `Typeclasses Opaque ghost_map_elem.` remove ~400 lines of useless attempts without stopping the real proof.

Backtrace:
```
The command has indeed failed with message:
Ltac call to "apply (ssrapplyarg)" failed.
Could not fill dependent hole in "apply"
Raised at Exninfo.iraise in file "clib/exninfo.ml" (inlined), line 79, characters 4-11
Called from Proofview.apply in file "engine/proofview.ml" (inlined), line 241, characters 21-59
Called from Proof.run_tactic in file "proofs/proof.ml", line 389, characters 4-49
Called from Proof.solve in file "proofs/proof.ml", line 498, characters 31-52
Called from ComTactic.solve_core.(fun) in file "vernac/comTactic.ml", line 46, characters 23-59
Called from Declare.Proof.map_fold_endline in file "vernac/declare.ml" (inlined), line 1445, characters 20-33
Called from ComTactic.solve_core in file "vernac/comTactic.ml" (inlined), line 43, characters 23-442
Called from ComTactic.solve_core in file "vernac/comTactic.ml", line 43, characters 23-442
Called from ComTactic.solve in file "vernac/comTactic.ml" (inlined), line 56, characters 2-44
Called from Ltac_plugin__G_ltac.coqpp_body in file "plugins/ltac/g_ltac.mlg" (inlined), line 409, characters 4-43
Called from Vernacextend.vtmodifyproof.(fun) in file "vernac/vernacextend.ml", line 152, characters 32-47
Called from Vernacinterp.interp_typed_vernac in file "vernac/vernacinterp.ml", line 20, characters 20-113
Called from Vernacinterp.interp_control.(fun) in file "vernac/vernacinterp.ml", line 215, characters 24-69
Called from Vernacinterp.interp_control_flag.(fun) in file "vernac/vernacinterp.ml" (inlined), line 132, characters 34-40
Called from Vernacinterp.with_fail in file "vernac/vernacinterp.ml", line 72, characters 12-16
```

Debug log: https://gist.github.com/Blaisorblade/f74742d5474bc873140fb1236c02cf3c.

**Comment by Blaisorblade** [comment]
Please recapture the backtrace for real use — mine isn't vanilla Coq 8.17, it's got @Janno secret sauce.

**Comment by SkySkimmer** [comment]
On master the debug says
~~~
Debug: 1.1: simple apply mapsto_as_fractional on
(AsFractional (l ↦{#q1} v) ?b q1) failed with: In environment
L : Type
V : Type
EqDecision0 : EqDecision L
H : Countable L
Σ : gFunctors
gen_heapGS0 : gen_heapGS L V Σ
p : bool
l : L
v : V
q1, q2, q : Qp
Unable to unify "λ q : Qp, (l ↦{#q} v)%I" with "λ q : Qp, (l ↦{#q} v)%I" (cannot satisfy constraint
"(λ q : Qp, (l ↦{#q} v)%I) q" == "unseal mapsto_aux l (DfracOwn q) v"; cannot unify 
"(l ↦{#q} v)%I" and
"unseal mapsto_aux l (DfracOwn q) v").
~~~

**Comment by RalfJung** [comment]
Okay, so that seems to confirm what Janno theorized above -- somewhere a heuristic is (unnecessarily) unfolding `mapsto` (arguably violating the fact that it is to be treated opaquely) and then later, *because* it is opaque, this unfolding is getting in the way.

**Comment by RalfJung** [comment]
@SkySkimmer how did you get that nice debug output (with the parenthetical explaining the unification failure)? Do I need to set some flags, or is this a Coq master thing that doesn't exist yet in 8.17?

**Comment by SkySkimmer** [comment]
Since https://github.com/coq/coq/pull/17325 (8.18)

**Comment by SkySkimmer** [comment]
(this issue seems quite similar to https://github.com/coq/coq/pull/17323 BTW)

**Comment by RalfJung** [comment]
It hasn't unfolded the sealed term itself, just the topmost `Definition`. Under regular conditions this is completely unnecessary but not a big deal, I think.

But here this happens in a unification context where that definition is marked opaque! And then unfolding it seems to clearly be a bug.

**Comment by SkySkimmer** [comment]
I guess this issue is fixed, the sealing issue can be opened separately.

**Comment by RalfJung** [comment]
What is it fixed by?

**Comment by RalfJung** [comment]
We still have TC unification unfolding a definition that it shouldn't unfold. That is what this bug is about, everything else is just getting to the bottom of that. And that hasn't been fixed, or has it?

**Comment by SkySkimmer** [comment]
This bug says the problem is the message "Cannot unify <term> and <identical term>" which is fixed by https://github.com/coq/coq/pull/17325

**Comment by RalfJung** [comment]
The bug is that this unification problem fails. Making the error better doesn't fix that bug.

But sure I can open a new issue if you prefer that.

**Comment by RalfJung** [comment]
New issue: https://github.com/coq/coq/issues/17720
