### ISSUE TITLE
Uncaught exception Pp_diff.Diff_Failure

### ISSUE THREAD

**Issue by eponier** [coq/coq#8922]
#### Version
master

#### Operating system
Fedora

#### Description of the problem

I tried the new feature that colours the changes in the goal, and encountered the following bug:
```
Lemma eza : True.
Proof.
  eassert(_).
  refine (fun _ => _).
```

```
Anomaly
"Uncaught exception Pp_diff.Diff_Failure("Unable to match goals betwen old and new proof states (6)")."
Please report at http://coq.inria.fr/bugs/.
```

**Comment by Zimmi48** [comment]
cc @jfehrle

**Comment by jfehrle** [comment]
@eponier Are you using CoqIDE as your interface?

**Comment by jfehrle** [comment]
The no hypothesis and no goal is incorrect printing caused by the diff code.  That I'll fix ASAP.

The goal-matching relies on a heuristic; I'll see what can be done to improve this.

Output with diffs on: 
```
2 subgoals
______________________________________(1/2)

______________________________________(2/2)
True
```

Output with diffs off:
```
2 subgoals
y : ?Goal0
______________________________________(1/2)
?Goal1@{x:=y}
______________________________________(2/2)
True
```

**Comment by jfehrle** [comment]
@ejgallego Would you take a look at this?  It looks like the output is different (see previous comment, above) because the diff code uses a `Constr.t` in `Proof_diffs.pp_of_type` and `process_goal`, whereas the original printer code calls `pr_letype_core`, which takes a `EConstr.constr = Evd.econstr`.  I think this is code you provided me a long while ago.

I've been debugging how `concl` gets printed in Printer.pr_goal.  I tried removing some of the `EConstr.to_constr` calls but so far haven't gotten it to typecheck with that change, let alone work correctly.

Do you have any ideas?

**Comment by jfehrle** [comment]
Fixed by https://github.com/coq/coq/pull/8967.

@eponier I hope you'll try the feature some more (if possible, before 8.9 ships).  Please let me know if you uncover any other issues or have suggestions about usability or other aspects.

**Comment by eponier** [comment]
Ok. Will have a look.

**Comment by eponier** [comment]
I have just tried my favourite example, and the goal no more disappears. However, I still get the anomaly

```
Anomaly
"Uncaught exception Pp_diff.Diff_Failure("Unable to match goals between old and new proof states (6)")."
Please report at http://coq.inria.fr/bugs/.
```

I this expected?

I will try to play more with the feature.

**Comment by jfehrle** [comment]
I will look at it again.  I thought I had it fixed for your example.

Goal matching for diffs uses a heuristic.  The exception is there for 2 reasons:
First, to uncover fixable cases that I didn't consider or encounter during development and
second, to inform users of cases where the heuristic isn't fixable--currently I'm not aware of any.

When you see this exception in CoqIDE, the context display isn't updated; the protocol doesn't let you return both the new context display and an exception.  The workaround is to select "Don't show diffs", which will update the context display (the Anomaly message is not cleared).  You can then re-enable diffs in subsequent steps of the proof.

When you see this exception in coqtop, the context is automatically displayed without diffs.

**Comment by eponier** [comment]
Another bug I have found is that when multiple hypotheses have the same type and they all disappear using one tactic, they are wrongly duplicated in mode "added and removed".

For instance,

```
Goal forall n m : nat, n = m.
Proof.
  intros. revert n m. (* here n m : nat is shown twice *)
```

But maybe I should open a new issue ?

**Comment by Zimmi48** [comment]
>second, to inform users of cases where the heuristic isn't fixable

Anomalies should not be used for this second case. Use another type of feedback in this case.

>But maybe I should open a new issue ?

Sounds like a good idea. In any case, the present issue needs to be reopened as well since the anomaly is still there (just confirmed this).

**Comment by eponier** [comment]
I opened https://github.com/coq/coq/issues/9091 for the second issue.

**Comment by jfehrle** [comment]
>>second, to inform users of cases where the heuristic isn't fixable

> Anomalies should not be used for this second case. Use another type of feedback in this case.

The second case is a bit theoretical.  At the moment I've not identified any such cases.  If we find any I'll update the code to handle them differently.
